

spring:
  datasource:
    url: jdbc:postgresql://ai-assistant-psql-db.postgres.database.azure.com:5432/postgres
    username: ktmediabizplatform
    password: aleldjqlwm12!@
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#spring:
#  datasource:
#    url: jdbc:mysql://mysqldb.c9g26yco4ajn.ap-northeast-2.rds.amazonaws.com:3306/chatbot_db
#    username: admin
#    password: 97777284a
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect


#  r2dbc:
#    url: r2dbc:mysql://mysqldb.c9g26yco4ajn.ap-northeast-2.rds.amazonaws.com:3306/chatbot_db
#    username: admin
#    password: 97777284a

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

webclient:
  flask-base-url: "http://localhost:5000"
